In [ ]:
# import necessary libraries
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving CASS_Spectrum_Dataset.csv to CASS_Spectrum_Dataset (1).csv

In [ ]:
df = pd.read_csv("CASS_Spectrum_Dataset.csv")

In [ ]:
df.head()

,time_index,freq_bin,power_dB,noise_type,noise_cluster_id,PU_Presence,PU_Signal_Strength,PU_bandwidth,PU_burst_duration,PU_drift_type,spectral_entropy,Frequency_Band,Cluster_ID,Cluster_Size,SNR_SU1,SNR_SU2,SNR_SU3
0,1,18,-55.091914,Broadband,40,0,-55.091914,12,Medium,Frequency drift,1.066,1800,40,12,11.542642,21.817575,19.299897
1,2,50,-63.195182,Narrowband,7,1,-63.195182,4,Medium,Frequency drift,1.042,5000,7,4,11.174470,24.917035,25.135808
2,3,50,-74.523619,Broadband,32,0,-74.523619,11,Medium,Bandwidth switch,1.037,5000,32,11,27.656365,11.261697,24.004023
3,4,18,-49.310249,Broadband,48,0,-49.310249,11,Medium,Frequency drift,1.032,1800,48,11,11.238655,20.621852,8.847498
4,5,24,-55.763441,Impulsive,19,0,-55.763441,7,Long,Frequency drift,1.044,2400,19,7,11.798743,19.293650,8.731237

In [ ]:
#check number of rows and columns in data
print("shape", df.shape)
print("columns", df.columns)
df.info()

shape (1000, 17)
columns Index(['time_index', 'freq_bin', 'power_dB', 'noise_type', 'noise_cluster_id',
       'PU_Presence', 'PU_Signal_Strength', 'PU_bandwidth',
       'PU_burst_duration', 'PU_drift_type', 'spectral_entropy',
       'Frequency_Band', 'Cluster_ID', 'Cluster_Size', 'SNR_SU1', 'SNR_SU2',
       'SNR_SU3'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   time_index          1000 non-null   int64
 1   freq_bin            1000 non-null   int64
 2   power_dB            1000 non-null   float64
 3   noise_type          1000 non-null   object
 4   noise_cluster_id    1000 non-null   int64
 5   PU_Presence         1000 non-null   int64
 6   PU_Signal_Strength  1000 non-null   float64
 7   PU_bandwidth        1000 non-null   int64
 8   PU_burst_duration   1000 non-null   object
 9   PU_drift_type       786 non-null    object
 10  spectral_entropy    1000 non-null   float64
 11  Frequency_Band      1000 non-null   int64
 12  Cluster_ID          1000 non-null   int64
 13  Cluster_Size        1000 non-null   int64
 14  SNR_SU1             1000 non-null   float64
 15  SNR_SU2             1000 non-null   float64
 16  SNR_SU3             1000 non-null   float64
dtypes: float64(6), int64(8), object(3)
memory usage: 132.9+ KB

In [ ]:
#check for missing values
df['PU_drift_type'] = df['PU_drift_type'].fillna('No Drift')

df.isnull().sum()
print("shape", df.shape)
print("columns", df.columns)

shape (1000, 17)
columns Index(['time_index', 'freq_bin', 'power_dB', 'noise_type', 'noise_cluster_id',
       'PU_Presence', 'PU_Signal_Strength', 'PU_bandwidth',
       'PU_burst_duration', 'PU_drift_type', 'spectral_entropy',
       'Frequency_Band', 'Cluster_ID', 'Cluster_Size', 'SNR_SU1', 'SNR_SU2',
       'SNR_SU3'],
      dtype='object')

In [ ]:
df = df.drop_duplicates()

In [ ]:
print(df.columns)
df.columns = df.columns.str.strip()

Index(['time_index', 'freq_bin', 'power_dB', 'noise_type', 'noise_cluster_id',
       'PU_Presence', 'PU_Signal_Strength', 'PU_bandwidth',
       'PU_burst_duration', 'PU_drift_type', 'spectral_entropy',
       'Frequency_Band', 'Cluster_ID', 'Cluster_Size', 'SNR_SU1', 'SNR_SU2',
       'SNR_SU3'],
      dtype='object')

In [ ]:
print(df['noise_type'].unique())

print(df['PU_burst_duration'].unique())

print(df['PU_drift_type'].unique())
df.head()

[0 2 1]
[1 0 2]
[1 0 2]

,time_index,freq_bin,power_dB,noise_type,noise_cluster_id,PU_Presence,PU_Signal_Strength,PU_bandwidth,PU_burst_duration,PU_drift_type,spectral_entropy,Frequency_Band,Cluster_ID,Cluster_Size,SNR_SU1,SNR_SU2,SNR_SU3
0,1,18,-55.091914,0,40,0,-55.091914,12,1,1,1.066,1800,40,12,11.542642,21.817575,19.299897
1,2,50,-63.195182,2,7,1,-63.195182,4,1,1,1.042,5000,7,4,11.174470,24.917035,25.135808
2,3,50,-74.523619,0,32,0,-74.523619,11,1,0,1.037,5000,32,11,27.656365,11.261697,24.004023
3,4,18,-49.310249,0,48,0,-49.310249,11,1,1,1.032,1800,48,11,11.238655,20.621852,8.847498
4,5,24,-55.763441,1,19,0,-55.763441,7,0,1,1.044,2400,19,7,11.798743,19.293650,8.731237

In [ ]:
#Convert text labels into numeric values.
le_noise = LabelEncoder()
le_burst = LabelEncoder()
le_drift = LabelEncoder()

df['noise_type'] = le_noise.fit_transform(df['noise_type'])

df['PU_burst_duration'] = le_burst.fit_transform(df['PU_burst_duration'])

df['PU_drift_type'] = le_drift.fit_transform(df['PU_drift_type'])

df.head()

,time_index,freq_bin,power_dB,noise_type,noise_cluster_id,PU_Presence,PU_Signal_Strength,PU_bandwidth,PU_burst_duration,PU_drift_type,spectral_entropy,Frequency_Band,Cluster_ID,Cluster_Size,SNR_SU1,SNR_SU2,SNR_SU3
0,1,18,-55.091914,0,40,0,-55.091914,12,1,1,1.066,1800,40,12,11.542642,21.817575,19.299897
1,2,50,-63.195182,2,7,1,-63.195182,4,1,1,1.042,5000,7,4,11.174470,24.917035,25.135808
2,3,50,-74.523619,0,32,0,-74.523619,11,1,0,1.037,5000,32,11,27.656365,11.261697,24.004023
3,4,18,-49.310249,0,48,0,-49.310249,11,1,1,1.032,1800,48,11,11.238655,20.621852,8.847498
4,5,24,-55.763441,1,19,0,-55.763441,7,0,1,1.044,2400,19,7,11.798743,19.293650,8.731237

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numerical_columns = [
    'PU_Presence', 'PU_Signal_Strength', 'Frequency_Band', 'SNR_SU1',
       'SNR_SU2', 'SNR_SU3', 'Cluster_ID', 'Cluster_Size', 'Pd', 'Pfa', 'Pmd',
        'Target'

]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   time_index          1000 non-null   int64
 1   freq_bin            1000 non-null   int64
 2   power_dB            1000 non-null   float64
 3   noise_type          1000 non-null   int64
 4   noise_cluster_id    1000 non-null   int64
 5   PU_Presence         1000 non-null   int64
 6   PU_Signal_Strength  1000 non-null   float64
 7   PU_bandwidth        1000 non-null   int64
 8   PU_burst_duration   1000 non-null   int64
 9   PU_drift_type       1000 non-null   int64
 10  spectral_entropy    1000 non-null   float64
 11  Frequency_Band      1000 non-null   int64
 12  Cluster_ID          1000 non-null   int64
 13  Cluster_Size        1000 non-null   int64
 14  SNR_SU1             1000 non-null   float64
 15  SNR_SU2             1000 non-null   float64
 16  SNR_SU3             1000 non-null   float64
dtypes: float64(6), int64(11)
memory usage: 132.9 KB

In [ ]:
#Define input features (X) and target variable (y). For spectrum occupancy prediction:

X = df.drop('PU_Presence', axis=1)

y = df['PU_Presence']

In [ ]:
df.to_csv("Cleaned_Spectrum_Dataset.csv", index=False)

In [ ]:
files.download("Cleaned_Spectrum_Dataset.csv")

In [ ]:
#split the data into training and testing modes
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(800, 16)
(200, 16)

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Convert the scaled arrays back to DataFrames for easier inspection
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=X_test.columns)

print("Scaled X_train (first 5 rows):")
display(X_train_scaled_df.head())

Scaled X_train (first 5 rows):

,time_index,freq_bin,power_dB,noise_type,noise_cluster_id,PU_Signal_Strength,PU_bandwidth,PU_burst_duration,PU_drift_type,spectral_entropy,Frequency_Band,Cluster_ID,Cluster_Size,SNR_SU1,SNR_SU2,SNR_SU3
0,1.706229,-1.067012,-0.938202,-1.186628,0.286450,-0.938202,1.289127,0.225499,0.159721,0.740849,-1.067012,0.286450,1.289127,0.195241,0.889134,-0.521457
1,1.182645,-1.067012,-0.833957,1.392998,-1.276813,-0.833957,-1.302807,-0.969198,0.159721,0.461714,-1.067012,-1.276813,-1.302807,-0.366914,0.116265,1.642155
2,-0.419108,-0.580856,-1.181965,-1.186628,-0.637296,-1.181965,1.001135,-0.969198,0.159721,0.443105,-0.580856,-0.637296,1.001135,-0.777622,0.978552,-0.022307
3,-0.794573,-1.067012,0.896230,-1.186628,0.073278,0.896230,1.001135,1.420196,1.519047,1.131639,-1.067012,0.073278,1.001135,0.332019,-0.084276,0.558897
4,1.713118,1.525822,0.351202,0.103185,1.210197,0.351202,0.137157,-0.969198,0.159721,-0.431521,1.525822,1.210197,0.137157,-1.281605,-0.020317,-1.484147

In [ ]:
#normalize numerical values
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [ ]:
#make scaled data easier to inspect
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X.columns
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X.columns
)

X_train_scaled.head()

,time_index,freq_bin,power_dB,noise_type,noise_cluster_id,PU_Signal_Strength,PU_bandwidth,PU_burst_duration,PU_drift_type,spectral_entropy,Frequency_Band,Cluster_ID,Cluster_Size,SNR_SU1,SNR_SU2,SNR_SU3
0,1.706229,-1.067012,-0.938202,-1.186628,0.286450,-0.938202,1.289127,0.225499,0.159721,0.740849,-1.067012,0.286450,1.289127,0.195241,0.889134,-0.521457
1,1.182645,-1.067012,-0.833957,1.392998,-1.276813,-0.833957,-1.302807,-0.969198,0.159721,0.461714,-1.067012,-1.276813,-1.302807,-0.366914,0.116265,1.642155
2,-0.419108,-0.580856,-1.181965,-1.186628,-0.637296,-1.181965,1.001135,-0.969198,0.159721,0.443105,-0.580856,-0.637296,1.001135,-0.777622,0.978552,-0.022307
3,-0.794573,-1.067012,0.896230,-1.186628,0.073278,0.896230,1.001135,1.420196,1.519047,1.131639,-1.067012,0.073278,1.001135,0.332019,-0.084276,0.558897
4,1.713118,1.525822,0.351202,0.103185,1.210197,0.351202,0.137157,-0.969198,0.159721,-0.431521,1.525822,1.210197,0.137157,-1.281605,-0.020317,-1.484147

In [ ]:
df.to_csv(
    '/content/CASS_Preprocessed.csv',
    index=False
)

print("Dataset saved successfully.")

Dataset saved successfully.

In [ ]:
files.download("/content/CASS_Preprocessed.csv")